# OS: Windows 10 Pro (64-bit)
# name: acc_win
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - _tflow_select=2.3.0
  - absl-py=1.4.0
  - aiofiles=22.1.0
  - aiohttp=3.8.5
  - aiosignal=1.2.0
  - aiosqlite=0.18.0
  - altair=5.0.1
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.6.2
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - ca-certificates=2023.08.22
  - cachetools=4.2.2
  - certifi=2023.7.22
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.2
  #- console_shortcut_miniconda=0.1.1
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.7
  - ds-lime=0.1.1.27
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - flatbuffers=2.0.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - gast=0.4.0
  - giflib=5.2.1
  - google-auth=2.22.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpcio=1.42.0
  - h5py=3.9.0
  - hdf5=1.12.1
  #- icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - imbalanced-learn=0.11.0
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=6.1.0
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_client=7.4.9
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=1.23.4
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.1
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.4
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.4.0
  - libdeflate=1.17
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxgboost=1.7.3
  - llvmlite=0.41.0
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - multidict=6.0.2
  - multiprocess=0.70.13
  - munkres=1.1.4
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.3
  - numba=0.58.0
  - numexpr=2.8.7
  - numpy=1.24.3
  - numpy-base=1.24.3
  - oauthlib=3.2.2
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - packaging=23.1
  - pandas=2.1.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathos=0.3.1
  - patsy=0.5.3
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3
  - platformdirs=3.10.0
  - pox=0.3.3
  - ppft=1.7.6.7
  - prince=0.10.8
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - protobuf=3.20.3
  - psutil=5.9.0
  - pure_eval=0.2.2
  - py-xgboost=1.7.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.15.1
  - pyjwt=2.4.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=2.0
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2023.3.post1
  #- pywin32=305
  #- pywinpty=2.0.10
  - pyyaml=6.0.1
  - pyzmq=23.2.0
  - referencing=0.30.2
  - requests=2.31.0
  - requests-oauthlib=1.3.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - rsa=4.7.2
  - scikit-learn=1.3.0
  - scipy=1.11.3
  - seaborn=0.12.2
  - send2trash=1.8.2
  - setuptools=68.0.0
  - shap=0.42.1
  - six=1.16.0
  - skater=1.0.2
  - slicer=0.0.7
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - statsmodels=0.14.0
  - tbb=2021.8.0
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - termcolor=2.1.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.18
  #- vc=14.2
  #- vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.3
  - wheel=0.41.2
  - win_inet_pton=1.1.0
  #- winpty=0.4.3
  - wrapt=1.14.1
  - xgboost=1.7.3
  - xz=5.4.2
  - y-py=0.5.9
  - yaml=0.2.5
  - yarl=1.8.1
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
